services:
  - type: web
    name: sirt-smart-library
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        value: 3MXYzq7tunmB4td.root
      - key: DB_PASSWORD
        value: r908TlL0fK5yNpYL
      - key: DB_NAME
        value: test
      - key: GEMINI_API_KEY
        value: AIzaSyAgEkMRY68rNKaFRrYBwNUkzyinsBsTyRY
